dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t $DOCKER_USERNAME/stable .
      - docker images
      - docker tag stable $DOCKER_USERNAME/stable
      - docker push $DOCKER_USERNAME/stable
    - stage: test
      script: docker run --rm $DOCKER_USERNAME/stable cat hello.txt
    - script: docker run --rm $DOCKER_USERNAME/stable cat hello.txt
