sudo: true
language: node
os: linux
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - docker build -t microservice-nano .
        - docker images
        - docker tag microservice-nano $DOCKER_USERNAME/microservice-nano
        - docker push $DOCKER_USERNAME/microservice-nano
